set $laptop_screen "eDP-1"
set $samsung_monitor "Samsung Electric Company U28E590 HTPKA00046"



output $samsung_monitor scale 1.25 mode 2560x1440 pos 0,0
output $laptop_screen scale 1.7777777 pos 0,0
output * bg $wallpaper fill


bindswitch --reload --locked lid:on output $laptop_screen disable
bindswitch --reload --locked lid:off output $laptop_screen enable

